#!/bin/csh -f

set cmd = "$HOME/bin/sources/neovim-qt/build/bin/nvim-qt"

#Check the number of args
if ( $#argv == 0 ) then
    echo "Nvim-qt cmd:  nvim-qt"
    $cmd
else
    if ( "$argv[1]" == "-d" ) then
        echo "Nvim-qt cmd: nvim-qt -- $argv"
        $cmd -- $argv
    else
        echo "Nvim-qt cmd: nvim-qt $argv"
        $cmd $argv
    endif
endif

